title:          Saadah
description:    ""
baseurl:        "/"
url:            "https://as-saadah.github.io"
markdown: kramdown
permalink: pretty
paginate: 20

defaults:
  # default en
  - values:
      locale: en
  # config posts
  - scope:
      path: "_posts/**"
      type: posts
    values:
      layout: post
      permalink: /:title
  - scope:
      path: _posts/ar/**
      type: posts
    values:
      layout: post
      locale: ar
      permalink: /ar/:title
